#PBS -m abe
#! /bin/bash


echo "Hello World!"
cd /icgc/dkfzlsdf/analysis/B080/steiger/scripts
#ls /icgc/dkfzlsdf/analysis/B080/steiger/data > ALL




echo "Calculating STAT for $data1 $data2 TCGA Data"

DATA="/icgc/dkfzlsdf/analysis/B080/steiger"
cd "$DATA/data"

echo ls
echo "Calculating Statistics"
Rscript-3.1.2 --vanilla /icgc/dkfzlsdf/analysis/B080/steiger/scripts/01CE_loadData.R $data1 $data2
Rscript-3.1.2 --vanilla /icgc/dkfzlsdf/analysis/B080/steiger/scripts/02CE_CorMX.R $data1 $data2
echo "Finished $data"
